# permissions for end users to edit caddyproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: caddyproxy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: caddy-operator
    app.kubernetes.io/part-of: caddy-operator
    app.kubernetes.io/managed-by: kustomize
  name: caddyproxy-editor-role
rules:
- apiGroups:
  - web.dev.fadur
  resources:
  - caddyproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.dev.fadur
  resources:
  - caddyproxies/status
  verbs:
  - get
